In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r'datasets\Diabetes prediction dataset.csv')

In [3]:
display(df)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [4]:
les = LabelEncoder()
leg = LabelEncoder()

In [5]:
dfa = df
dfa['smoking_history'] = les.fit_transform(df['smoking_history'])
dfa['gender'] = les.fit_transform(df['gender'])

In [6]:
display(dfa)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,4,25.19,6.6,140,0
1,0,54.0,0,0,0,27.32,6.6,80,0
2,1,28.0,0,0,4,27.32,5.7,158,0
3,0,36.0,0,0,1,23.45,5.0,155,0
4,1,76.0,1,1,1,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,0,80.0,0,0,0,27.32,6.2,90,0
99996,0,2.0,0,0,0,17.37,6.5,100,0
99997,1,66.0,0,0,3,27.83,5.7,155,0
99998,0,24.0,0,0,4,35.42,4.0,100,0
99999,0,57.0,0,0,1,22.43,6.6,90,0

In [7]:
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(dfa), columns=dfa.columns)

In [9]:
#scaler.feature_names_in_
scaler.mean_

array([4.14660000e-01, 4.18858560e+01, 7.48500000e-02, 3.94200000e-02,
       2.17965000e+00, 2.73207671e+01, 5.52750700e+00, 1.38058060e+02,
       8.50000000e-02])

In [72]:
display(df_scaled)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes,Cluster
0,-0.841047,1.692704,-0.284439,4.936379,0.963327,-0.321056,1.001706,0.047704,-0.304789,2
1,-0.841047,0.538006,-0.284439,-0.202578,-1.153468,-0.000116,1.001706,-1.426210,-0.304789,1
2,1.187234,-0.616691,-0.284439,-0.202578,0.963327,-0.000116,0.161108,0.489878,-0.304789,2
3,-0.841047,-0.261399,-0.284439,-0.202578,-0.624269,-0.583232,-0.492690,0.416183,-0.304789,1
4,1.187234,1.515058,3.515687,4.936379,-0.624269,-1.081970,-0.679490,0.416183,-0.304789,2
...,...,...,...,...,...,...,...,...,...,...
99995,-0.841047,1.692704,-0.284439,-0.202578,-1.153468,-0.000116,0.628107,-1.180558,-0.304789,1
99996,-0.841047,-1.771388,-0.284439,-0.202578,-1.153468,-1.499343,0.908306,-0.934905,-0.304789,1
99997,1.187234,1.070944,-0.284439,-0.202578,0.434128,0.076729,0.161108,0.416183,-0.304789,2
99998,-0.841047,-0.794336,-0.284439,-0.202578,0.963327,1.220361,-1.426688,-0.934905,-0.304789,2
99999,-0.841047,0.671241,-0.284439,-0.202578,-0.624269,-0.736922,1.001706,-1.180558,-0.304789,1

In [73]:
kmeans = KMeans(n_clusters=3, random_state=1234, n_init=10)
df_scaled['Cluster'] = kmeans.fit_predict(df_scaled)

# Add cluster labels to original data
df['Cluster'] = df_scaled['Cluster']

In [ ]:
sns.pairplot(df, hue="Cluster", palette="viridis", diag_kind="kde")
plt.show()

KeyboardInterrupt: